require('dotenv').config();
const crypto = require('crypto');
const express = require('express');
const path = require('path');
const sqlite3 = require('sqlite3').verbose();

const app = express();
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const BOT_USERNAME = process.env.TELEGRAM_BOT_USERNAME || 'arzmodsbot';
const ENVIRONMENT = process.env.NODE_ENV || 'development';
const DATABASE_URL = process.env.DATABASE_URL || '';
const USE_POSTGRES = Boolean(DATABASE_URL);
const DATA_DIR = path.join(__dirname, 'data');
const DB_PATH = path.join(DATA_DIR, 'app.db');

let db = null;
let pgClient = null;

if (USE_POSTGRES) {
  const { Client } = require('pg');
  pgClient = new Client({
    connectionString: DATABASE_URL,
    ssl: ENVIRONMENT === 'production' ? { rejectUnauthorized: false } : false
  });
}

if (!USE_POSTGRES) {
  db = new sqlite3.Database(DB_PATH);
}

app.disable('x-powered-by');
app.set('trust proxy', 1);

app.use(express.json({ limit: '1mb' }));
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.sendStatus(204);
  }

  next();
});
app.use(express.static(path.join(__dirname, 'public')));

async function connectDatabase() {
  if (pgClient) {
    await pgClient.connect();
  }
}

function runSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => ({
      id: result.rows[0]?.id ?? null,
      changes: result.rowCount ?? 0,
      rows: result.rows || []
    }));
  }

  return new Promise((resolve, reject) => {
    db.run(sql, params, function onComplete(err) {
      if (err) {
        reject(err);
        return;
      }
      resolve({ id: this.lastID, changes: this.changes, rows: [] });
    });
  });
}

function getSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => result.rows[0] || null);
  }

  return new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(row || null);
    });
  });
}

function allSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => result.rows || []);
  }

  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(rows || []);
    });
  });
}

async function initDatabase() {
  if (USE_POSTGRES) {
    await connectDatabase();
    await runSql(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nickname TEXT,
        telegram TEXT UNIQUE,
        discord TEXT,
        auth_source TEXT DEFAULT 'manual',
        packages_count INTEGER DEFAULT 6,
        balance INTEGER DEFAULT 420,
        rating DOUBLE PRECISION DEFAULT 4.9,
        downloads INTEGER DEFAULT 12000,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      )
    `);

    const currentUser = await getSql('SELECT id FROM users LIMIT 1');
    if (!currentUser) {
      await runSql(
        `INSERT INTO users (nickname, telegram, discord, auth_source, packages_count, balance, rating, downloads)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
        ['AZRider_77', '@arzmodsbot', 'discord', 'demo', 6, 420, 4.9, 12000]
      );
    }
    return;
  }

  await runSql(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      nickname TEXT,
      telegram TEXT UNIQUE,
      discord TEXT,
      auth_source TEXT DEFAULT 'manual',
      packages_count INTEGER DEFAULT 6,
      balance INTEGER DEFAULT 420,
      rating REAL DEFAULT 4.9,
      downloads INTEGER DEFAULT 12000,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);

  const currentUser = await getSql('SELECT id FROM users LIMIT 1');
  if (!currentUser) {
    await runSql(
      `INSERT INTO users (nickname, telegram, discord, auth_source, packages_count, balance, rating, downloads)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      ['AZRider_77', '@arzmodsbot', 'discord', 'demo', 6, 420, 4.9, 12000]
    );
  }
}

function normalizeProfile(body = {}) {
  return {
    nickname: String(body.nickname || '').trim(),
    telegram: String(body.telegram || '').trim(),
    discord: String(body.discord || '').trim(),
    authSource: body.authSource || 'manual'
  };
}

async function upsertProfile(profile) {
  const nickname = profile.nickname || 'TelegramUser';
  const telegram = profile.telegram || '';
  const discord = profile.discord || '';
  const authSource = profile.authSource || 'manual';

  if (USE_POSTGRES) {
    const existing = telegram
      ? await getSql('SELECT * FROM users WHERE telegram = $1', [telegram])
      : await getSql('SELECT * FROM users WHERE nickname = $1', [nickname]);

    if (existing) {
      const result = await runSql(
        `UPDATE users
         SET nickname = $1, telegram = $2, discord = $3, auth_source = $4, updated_at = NOW()
         WHERE id = $5
         RETURNING *`,
        [nickname, telegram || existing.telegram, discord || existing.discord || '', authSource, existing.id]
      );
      return result.rows && result.rows[0] ? result.rows[0] : await getSql('SELECT * FROM users WHERE id = $1', [existing.id]);
    }

    const result = await runSql(
      `INSERT INTO users (nickname, telegram, discord, auth_source, packages_count, balance, rating, downloads)
       VALUES ($1, $2, $3, $4, 6, 420, 4.9, 12000)
       RETURNING *`,
      [nickname, telegram, discord, authSource]
    );

    return result.rows && result.rows[0] ? result.rows[0] : await getSql('SELECT * FROM users WHERE telegram = $1 OR nickname = $2', [telegram, nickname]);
  }

  const existing = telegram
    ? await getSql('SELECT * FROM users WHERE telegram = ?', [telegram])
    : await getSql('SELECT * FROM users WHERE nickname = ?', [nickname]);

  if (existing) {
    await runSql(
      `UPDATE users
       SET nickname = ?, telegram = ?, discord = ?, auth_source = ?, updated_at = CURRENT_TIMESTAMP
       WHERE id = ?`,
      [nickname, telegram || existing.telegram, discord || existing.discord || '', authSource, existing.id]
    );

    return await getSql('SELECT * FROM users WHERE id = ?', [existing.id]);
  }

  await runSql(
    `INSERT INTO users (nickname, telegram, discord, auth_source, packages_count, balance, rating, downloads)
     VALUES (?, ?, ?, ?, 6, 420, 4.9, 12000)`,
    [nickname, telegram, discord, authSource]
  );

  return await getSql('SELECT * FROM users WHERE telegram = ? OR nickname = ?', [telegram, nickname]);
}

function isTelegramDataValid(data) {
  if (!BOT_TOKEN || !data || !data.hash) {
    return false;
  }

  const authDate = Number(data.auth_date || 0);
  if (!Number.isFinite(authDate) || Date.now() / 1000 - authDate > 86400) {
    return false;
  }

  const sortedKeys = Object.keys(data)
    .filter((key) => key !== 'hash' && data[key] !== undefined && data[key] !== null)
    .sort((a, b) => a.localeCompare(b));

  const checkString = sortedKeys.map((key) => `${key}=${data[key]}`).join('\n');
  const secretKey = crypto.createHash('sha256').update(BOT_TOKEN).digest();
  const computedHash = crypto.createHmac('sha256', secretKey).update(checkString).digest('hex');

  if (computedHash.length !== data.hash.length) {
    return false;
  }

  try {
    return crypto.timingSafeEqual(Buffer.from(computedHash, 'hex'), Buffer.from(data.hash, 'hex'));
  } catch (error) {
    return false;
  }
}

app.get('/api/profile', async (req, res) => {
  const row = await getSql('SELECT * FROM users ORDER BY id DESC LIMIT 1');
  res.json(row || { nickname: '', telegram: '', discord: '', auth_source: 'manual' });
});

app.get('/api/dashboard', async (req, res) => {
  const row = await getSql('SELECT * FROM users ORDER BY id DESC LIMIT 1');
  const profile = row || {
    nickname: 'AZRider_77',
    telegram: '@arzmodsbot',
    discord: '',
    auth_source: 'demo',
    packages_count: 6,
    balance: 420,
    rating: 4.9,
    downloads: 12000
  };

  res.json({
    profile: {
      nickname: profile.nickname,
      telegram: profile.telegram,
      discord: profile.discord,
      authSource: profile.auth_source,
      packagesCount: Number(profile.packages_count ?? 6),
      balance: Number(profile.balance ?? 420),
      rating: Number(profile.rating ?? 4.9),
      downloads: Number(profile.downloads ?? 12000)
    }
  });
});

app.post('/api/profile', async (req, res) => {
  const profile = normalizeProfile(req.body || {});

  if (!profile.nickname && !profile.telegram) {
    return res.status(400).json({ success: false, message: 'nickname or telegram is required' });
  }

  const saved = await upsertProfile(profile);
  return res.json({ success: true, profile: {
    nickname: saved.nickname,
    telegram: saved.telegram,
    discord: saved.discord,
    authSource: saved.auth_source,
    packagesCount: Number(saved.packages_count ?? 6),
    balance: Number(saved.balance ?? 420),
    rating: Number(saved.rating ?? 4.9),
    downloads: Number(saved.downloads ?? 12000)
  }});
});

app.post('/api/telegram-auth', async (req, res) => {
  const payload = req.body || {};
  if (!isTelegramDataValid(payload)) {
    return res.status(401).json({ success: false, message: 'Telegram auth validation failed' });
  }

  const nickname = payload.username || payload.first_name || 'TelegramUser';
  const telegram = payload.username ? `@${payload.username}` : `id:${payload.id}`;

  const saved = await upsertProfile({
    nickname,
    telegram,
    discord: '',
    authSource: 'telegram'
  });

  return res.json({ success: true, profile: {
    nickname: saved.nickname,
    telegram: saved.telegram,
    discord: saved.discord,
    authSource: saved.auth_source,
    packagesCount: Number(saved.packages_count ?? 6),
    balance: Number(saved.balance ?? 420),
    rating: Number(saved.rating ?? 4.9),
    downloads: Number(saved.downloads ?? 12000)
  }});
});

app.get('/api/config', (req, res) => {
  res.json({
    botUsername: BOT_USERNAME,
    demoMode: !BOT_TOKEN,
    telegramLoginEnabled: Boolean(BOT_TOKEN),
    environment: ENVIRONMENT,
    note: BOT_TOKEN
      ? 'Telegram Login is enabled using the configured bot token.'
      : 'Set TELEGRAM_BOT_TOKEN to enable real Telegram Login.'
  });
});

app.get('/api/health', (req, res) => {
  res.json({
    ok: true,
    status: 'healthy',
    environment: ENVIRONMENT,
    botEnabled: Boolean(BOT_TOKEN),
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

async function startServer() {
  await initDatabase();

  const server = app.listen(PORT, HOST, () => {
    const url = `http://${HOST === '0.0.0.0' ? 'localhost' : HOST}:${PORT}`;
    console.log(`AZRP Mods app running at ${url}`);
    console.log(`Environment: ${ENVIRONMENT}`);
    console.log(`Telegram auth: ${BOT_TOKEN ? 'enabled' : 'disabled'}`);

    if (!BOT_TOKEN) {
      console.warn('Warning: Telegram auth is disabled. Set TELEGRAM_BOT_TOKEN and TELEGRAM_BOT_USERNAME for production use.');
    }
  });

  server.keepAliveTimeout = 65 * 1000;
  server.headersTimeout = 70 * 1000;
}

startServer().catch((error) => {
  console.error('Failed to start server:', error);
  process.exit(1);
});
