require('dotenv').config();
const crypto = require('crypto');
const express = require('express');
const fs = require('fs');
const path = require('path');
const sqlite3 = require('sqlite3').verbose();

const app = express();
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const BOT_USERNAME = process.env.TELEGRAM_BOT_USERNAME || 'arzmodsbot';
const ENVIRONMENT = process.env.NODE_ENV || 'development';
const DATABASE_URL = process.env.DATABASE_URL || '';
const USE_POSTGRES = Boolean(DATABASE_URL);
const DATA_DIR = path.join(__dirname, 'data');
const DB_PATH = process.env.SQLITE_DB_PATH || path.join(DATA_DIR, 'app.db');
const SESSION_COOKIE = 'azrp_session';
const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;

let db = null;
let pgClient = null;

if (USE_POSTGRES) {
  const { Client } = require('pg');
  pgClient = new Client({
    connectionString: DATABASE_URL,
    ssl: ENVIRONMENT === 'production' ? { rejectUnauthorized: false } : false
  });
}

if (!USE_POSTGRES) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  db = new sqlite3.Database(DB_PATH);
}

app.disable('x-powered-by');
app.set('trust proxy', 1);

app.use(express.json({ limit: '1mb' }));
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.sendStatus(204);
  }

  next();
});
app.use(express.static(path.join(__dirname, 'public')));

async function connectDatabase() {
  if (pgClient) {
    await pgClient.connect();
  }
}

function runSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => ({
      id: result.rows[0]?.id ?? null,
      changes: result.rowCount ?? 0,
      rows: result.rows || []
    }));
  }

  return new Promise((resolve, reject) => {
    db.run(sql, params, function onComplete(err) {
      if (err) {
        reject(err);
        return;
      }
      resolve({ id: this.lastID, changes: this.changes, rows: [] });
    });
  });
}

function getSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => result.rows[0] || null);
  }

  return new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(row || null);
    });
  });
}

function allSql(sql, params = []) {
  if (USE_POSTGRES && pgClient) {
    return pgClient.query(sql, params).then((result) => result.rows || []);
  }

  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(rows || []);
    });
  });
}

async function initDatabase() {
  if (USE_POSTGRES) {
    await connectDatabase();
    await runSql(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nickname TEXT,
        telegram TEXT UNIQUE,
        discord TEXT,
        auth_source TEXT DEFAULT 'manual',
        packages_count INTEGER DEFAULT 0,
        balance INTEGER DEFAULT 0,
        rating DOUBLE PRECISION DEFAULT 0,
        downloads INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      )
    `);

    return;
  }

  await runSql(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      nickname TEXT,
      telegram TEXT UNIQUE,
      discord TEXT,
      auth_source TEXT DEFAULT 'manual',
      packages_count INTEGER DEFAULT 0,
      balance INTEGER DEFAULT 0,
      rating REAL DEFAULT 0,
      downloads INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);

}

function normalizeProfile(body = {}) {
  return {
    nickname: String(body.nickname || '').trim(),
    telegram: String(body.telegram || '').trim(),
    discord: String(body.discord || '').trim(),
    authSource: body.authSource || 'manual'
  };
}

function createSessionCookie(userId) {
  const expiresAt = Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS;
  const value = `${userId}.${expiresAt}`;
  const signature = crypto.createHmac('sha256', BOT_TOKEN).update(value).digest('hex');
  const secure = ENVIRONMENT === 'production' ? '; Secure' : '';
  return `${SESSION_COOKIE}=${value}.${signature}; Max-Age=${SESSION_TTL_SECONDS}; Path=/; HttpOnly; SameSite=Lax${secure}`;
}

function getSessionUserId(req) {
  if (!BOT_TOKEN) return null;

  const cookies = (req.headers.cookie || '').split(';');
  const cookie = cookies.map((part) => part.trim()).find((part) => part.startsWith(`${SESSION_COOKIE}=`));
  if (!cookie) return null;

  const [userId, expiresAt, signature, ...extra] = cookie.slice(SESSION_COOKIE.length + 1).split('.');
  if (extra.length || !/^\d+$/.test(userId) || !/^\d+$/.test(expiresAt)) return null;
  if (Number(expiresAt) <= Math.floor(Date.now() / 1000)) return null;

  const value = `${userId}.${expiresAt}`;
  const expected = crypto.createHmac('sha256', BOT_TOKEN).update(value).digest();
  let received;
  try {
    received = Buffer.from(signature, 'hex');
  } catch {
    return null;
  }

  if (received.length !== expected.length || !crypto.timingSafeEqual(received, expected)) return null;
  return Number(userId);
}

function publicProfile(profile) {
  return {
    id: profile.id,
    nickname: profile.nickname,
    telegram: profile.telegram,
    authSource: profile.auth_source,
    createdAt: profile.created_at
  };
}

async function upsertProfile(profile) {
  const nickname = profile.nickname || 'TelegramUser';
  const telegram = profile.telegram || '';
  const discord = profile.discord || '';
  const authSource = profile.authSource || 'manual';

  if (USE_POSTGRES) {
    const existing = telegram
      ? await getSql('SELECT * FROM users WHERE telegram = $1', [telegram])
      : await getSql('SELECT * FROM users WHERE nickname = $1', [nickname]);

    if (existing) {
      const result = await runSql(
        `UPDATE users
         SET nickname = $1, telegram = $2, discord = $3, auth_source = $4, updated_at = NOW()
         WHERE id = $5
         RETURNING *`,
        [nickname, telegram || existing.telegram, discord || existing.discord || '', authSource, existing.id]
      );
      return result.rows && result.rows[0] ? result.rows[0] : await getSql('SELECT * FROM users WHERE id = $1', [existing.id]);
    }

    const result = await runSql(
      `INSERT INTO users (nickname, telegram, discord, auth_source)
       VALUES ($1, $2, $3, $4)
       RETURNING *`,
      [nickname, telegram, discord, authSource]
    );

    return result.rows && result.rows[0] ? result.rows[0] : await getSql('SELECT * FROM users WHERE telegram = $1 OR nickname = $2', [telegram, nickname]);
  }

  const existing = telegram
    ? await getSql('SELECT * FROM users WHERE telegram = ?', [telegram])
    : await getSql('SELECT * FROM users WHERE nickname = ?', [nickname]);

  if (existing) {
    await runSql(
      `UPDATE users
       SET nickname = ?, telegram = ?, discord = ?, auth_source = ?, updated_at = CURRENT_TIMESTAMP
       WHERE id = ?`,
      [nickname, telegram || existing.telegram, discord || existing.discord || '', authSource, existing.id]
    );

    return await getSql('SELECT * FROM users WHERE id = ?', [existing.id]);
  }

  await runSql(
    `INSERT INTO users (nickname, telegram, discord, auth_source)
     VALUES (?, ?, ?, ?)`,
    [nickname, telegram, discord, authSource]
  );

  return await getSql('SELECT * FROM users WHERE telegram = ? OR nickname = ?', [telegram, nickname]);
}

function isTelegramDataValid(data) {
  if (!BOT_TOKEN || !data || !data.hash) {
    return false;
  }

  const authDate = Number(data.auth_date || 0);
  if (!Number.isFinite(authDate) || Date.now() / 1000 - authDate > 86400) {
    return false;
  }

  const sortedKeys = Object.keys(data)
    .filter((key) => key !== 'hash' && data[key] !== undefined && data[key] !== null)
    .sort((a, b) => a.localeCompare(b));

  const checkString = sortedKeys.map((key) => `${key}=${data[key]}`).join('\n');
  const secretKey = crypto.createHash('sha256').update(BOT_TOKEN).digest();
  const computedHash = crypto.createHmac('sha256', secretKey).update(checkString).digest('hex');

  if (computedHash.length !== data.hash.length) {
    return false;
  }

  try {
    return crypto.timingSafeEqual(Buffer.from(computedHash, 'hex'), Buffer.from(data.hash, 'hex'));
  } catch (error) {
    return false;
  }
}

app.get('/api/profile', async (req, res) => {
  const userId = getSessionUserId(req);
  if (!userId) return res.status(401).json({ success: false, message: 'Authentication required' });

  const row = await getSql(
    USE_POSTGRES ? 'SELECT * FROM users WHERE id = $1' : 'SELECT * FROM users WHERE id = ?',
    [userId]
  );
  return res.json(row ? publicProfile(row) : null);
});

app.get('/api/dashboard', async (req, res) => {
  const userId = getSessionUserId(req);
  if (!userId) return res.json({ profile: null });

  const row = await getSql(
    USE_POSTGRES ? 'SELECT * FROM users WHERE id = $1' : 'SELECT * FROM users WHERE id = ?',
    [userId]
  );
  return res.json({ profile: row ? publicProfile(row) : null });
});

app.post('/api/profile', async (req, res) => {
  const userId = getSessionUserId(req);
  if (!userId) return res.status(401).json({ success: false, message: 'Authentication required' });

  const profile = normalizeProfile(req.body || {});
  if (!profile.nickname) return res.status(400).json({ success: false, message: 'nickname is required' });

  const saved = await getSql(
    USE_POSTGRES
      ? `UPDATE users SET nickname = $1, discord = $2, updated_at = NOW() WHERE id = $3 RETURNING *`
      : `UPDATE users SET nickname = ?, discord = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING *`,
    [profile.nickname, profile.discord, userId]
  );
  if (!saved) return res.status(404).json({ success: false, message: 'Profile not found' });
  return res.json({ success: true, profile: publicProfile(saved) });
});

app.post('/api/telegram-auth', async (req, res) => {
  const payload = req.body || {};
  if (!isTelegramDataValid(payload)) {
    return res.status(401).json({ success: false, message: 'Telegram auth validation failed' });
  }

  const nickname = payload.username || payload.first_name || 'TelegramUser';
  const telegram = payload.username ? `@${payload.username}` : `id:${payload.id}`;

  const saved = await upsertProfile({
    nickname,
    telegram,
    discord: '',
    authSource: 'telegram'
  });

  res.setHeader('Set-Cookie', createSessionCookie(saved.id));
  return res.json({ success: true, profile: publicProfile(saved) });
});

app.post('/api/logout', (req, res) => {
  const secure = ENVIRONMENT === 'production' ? '; Secure' : '';
  res.setHeader('Set-Cookie', `${SESSION_COOKIE}=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax${secure}`);
  return res.json({ success: true });
});

app.get('/api/config', (req, res) => {
  res.json({
    botUsername: BOT_USERNAME,
    demoMode: !BOT_TOKEN,
    telegramLoginEnabled: Boolean(BOT_TOKEN),
    environment: ENVIRONMENT,
    note: BOT_TOKEN
      ? 'Telegram Login is enabled using the configured bot token.'
      : 'Set TELEGRAM_BOT_TOKEN to enable real Telegram Login.'
  });
});

app.get('/api/health', (req, res) => {
  res.json({
    ok: true,
    status: 'healthy',
    environment: ENVIRONMENT,
    botEnabled: Boolean(BOT_TOKEN),
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

async function startServer() {
  await initDatabase();

  const server = app.listen(PORT, HOST, () => {
    const url = `http://${HOST === '0.0.0.0' ? 'localhost' : HOST}:${PORT}`;
    console.log(`AZRP Mods app running at ${url}`);
    console.log(`Environment: ${ENVIRONMENT}`);
    console.log(`Telegram auth: ${BOT_TOKEN ? 'enabled' : 'disabled'}`);

    if (!BOT_TOKEN) {
      console.warn('Warning: Telegram auth is disabled. Set TELEGRAM_BOT_TOKEN and TELEGRAM_BOT_USERNAME for production use.');
    }
  });

  server.keepAliveTimeout = 65 * 1000;
  server.headersTimeout = 70 * 1000;
}

startServer().catch((error) => {
  console.error('Failed to start server:', error);
  process.exit(1);
});
